# @format

sudo: required
services:
  - docker

before_install:
  - docker build -t hamzazahid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamzazahid/react-test npm test -- --coverage

after_success:
  - docker build -t hamzazahid/multi-client ./client
  - docker build -t hamzazahid/multi-nginx ./nginx
  - docker build -t hamzazahid/multi-server ./server
  - docker build -t hamzazahid/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push hamzazahid/multi-client
  - docker push hamzazahid/multi-nginx
  - docker push hamzazahid/multi-server
  - docker push hamzazahid/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-703004911044
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
